You will be provided with a partial code base and an issue statement explaining a problem to resolve.

<issue>
Executable User Defined Functions used by aggregate function error "Unknown function"
Always reproduced (ClickHouse server version 22.3.2.1):
`
udf code, python version 3.9.6
#!/usr/bin/python

import sys
import time

if __name__ == '__main__':
    for line in sys.stdin:
        print("Python4 " + line, end='')
        sys.stdout.flush()
`

SELECT test_function_python('clickhouse')

Query id: 57da3834-1238-4da6-a984-48d4c1bb4a04

┌─test_function_python('clickhouse')─┐
│ Python4 clickhouse                 │
└────────────────────────────────────┘

1 rows in set. Elapsed: 0.001 sec.

SELECT test_function_python('clickhouse') AS uuu
GROUP BY uuu

Query id: c14131e5-e7aa-4585-a9f5-8e4b3e29fe44


0 rows in set. Elapsed: 0.002 sec.

Received exception from server (version 22.3.2):
Code: 46. DB::Exception: Received from 10.254.134.108:9000. DB::Exception: Unknown function test_function_python. (UNKNOWN_FUNCTION)


SELECT uuu
FROM
(
    SELECT test_function_python('clickhouse') AS uuu
) AS tmp
GROUP BY uuu

Query id: 20ca737b-35e1-418a-ab8e-2a296ac44e28

┌─uuu────────────────┐
│ Python4 clickhouse │
└────────────────────┘

1 rows in set. Elapsed: 0.002 sec.
</issue>

I need you to solve the provided issue by generating a code fix that can be applied directly to the repository

Respond below:
