You will be provided with a partial code base and an issue statement explaining a problem to resolve.

<issue>
Usage of lambda functions in an ALTER UPDATE results in an exception.
Hello. We've attempted to provide an `ALTER` to our 19.17.4 ReplicatedMergeTree table and are receiving this error:
```sql
ALTER TABLE transactions_local
    UPDATE _tags_flattened = concat('|', arrayStringConcat(arrayMap((k, v) -> concat(k, '=', v), `tags.key`, `tags.value`), '||'), '|') WHERE _tags_flattened = ''


Received exception from server (version 19.17.4):
Code: 46. DB::Exception: Received from localhost:9000. DB::Exception: Unknown function lambda.
```

The alter can be applied in local development, and the statement is valid when running a similar SELECT:
```sql
SELECT concat('|', arrayStringConcat(arrayMap((k, v) -> concat(k, '=', v), `tags.key`, `tags.value`), '||'), '|') AS _tags_flattened
FROM transactions_local
LIMIT 1
FORMAT Vertical

Row 1:
──────
_tags_flattened: |browser=Chrome 77.0.3865||browser.name=Chrome||client_os.name=Linux||interface_type=spans||level=error||runtime=CPython 3.6.7||runtime.name=CPython||sentry:release=*******||sentry:user=id:1||server_name=local-app||trace=090c77136de045618056ab4dd3ec3140||trace.ctx=090c77136de045618056ab4dd3ec3140-b602b78be05a5dfa||trace.span=b602b78be05a5dfa||transaction=/jsreverse/||url=****|
```

I'll be happy to provide any additional information. We've been attempting to reproduce this with our local machines but cannot yet.
</issue>

I need you to solve the provided issue by generating a code fix that can be applied directly to the repository

Respond below:
