{
  "repo": "duckdb/duckdb",
  "pull_number": 14289,
  "instance_id": "duckdb__duckdb-14289",
  "issue_numbers": [
    "14286",
    "14286"
  ],
  "base_commit": "8cec9b1537f900e7a644e7b466ea899cf1ca8f8f",
  "patch": "diff --git a/src/execution/operator/aggregate/physical_hash_aggregate.cpp b/src/execution/operator/aggregate/physical_hash_aggregate.cpp\nindex c4cf4b55d0b0..e7d0c7563c55 100644\n--- a/src/execution/operator/aggregate/physical_hash_aggregate.cpp\n+++ b/src/execution/operator/aggregate/physical_hash_aggregate.cpp\n@@ -319,15 +319,17 @@ void PhysicalHashAggregate::SinkDistinctGrouping(ExecutionContext &context, Data\n \t\t\tfor (idx_t group_idx = 0; group_idx < grouped_aggregate_data.groups.size(); group_idx++) {\n \t\t\t\tauto &group = grouped_aggregate_data.groups[group_idx];\n \t\t\t\tauto &bound_ref = group->Cast<BoundReferenceExpression>();\n-\t\t\t\tfiltered_input.data[bound_ref.index].Reference(chunk.data[bound_ref.index]);\n+\t\t\t\tauto &col = filtered_input.data[bound_ref.index];\n+\t\t\t\tcol.Reference(chunk.data[bound_ref.index]);\n+\t\t\t\tcol.Slice(sel_vec, count);\n \t\t\t}\n \t\t\tfor (idx_t child_idx = 0; child_idx < aggregate.children.size(); child_idx++) {\n \t\t\t\tauto &child = aggregate.children[child_idx];\n \t\t\t\tauto &bound_ref = child->Cast<BoundReferenceExpression>();\n-\n-\t\t\t\tfiltered_input.data[bound_ref.index].Reference(chunk.data[bound_ref.index]);\n+\t\t\t\tauto &col = filtered_input.data[bound_ref.index];\n+\t\t\t\tcol.Reference(chunk.data[bound_ref.index]);\n+\t\t\t\tcol.Slice(sel_vec, count);\n \t\t\t}\n-\t\t\tfiltered_input.Slice(sel_vec, count);\n \t\t\tfiltered_input.SetCardinality(count);\n \n \t\t\tradix_table.Sink(context, filtered_input, sink_input, empty_chunk, empty_filter);\n",
  "test_patch": "diff --git a/test/issues/general/test_14232.test b/test/issues/general/test_14232.test\nindex 2c6664ccbfb5..35fc46de7dbf 100644\n--- a/test/issues/general/test_14232.test\n+++ b/test/issues/general/test_14232.test\n@@ -59,7 +59,7 @@ INSERT INTO t2 (t2a, t2b, t2c, t2d, t2e, t2f, t2g, t2h, t2i) VALUES\n ('t1f', 19, NULL, 19, 17.0, 25, 26.00, '2014-10-04 01:01:00', '2014-10-04'),\n ('t1b', NULL, 16, 19, 17.0, 25, 26.00, '2014-05-04 01:01:00', NULL)\n \n-query II\n+query II rowsort\n SELECT t1a,\n t1b\n FROM t1\ndiff --git a/test/issues/general/test_14286.test b/test/issues/general/test_14286.test\nnew file mode 100644\nindex 000000000000..1cf3095789b1\n--- /dev/null\n+++ b/test/issues/general/test_14286.test\n@@ -0,0 +1,16 @@\n+# name: test/issues/general/test_14286.test\n+# description: Issue 14286 - An error was encountered using both distinct and struct\n+# group: [general]\n+\n+statement ok\n+select\n+    category,\n+    array_agg(distinct name) filter(where id != 5)            as a_list,\n+    array_agg(name)          filter(where id != 5)            as b_list,\n+    array_agg({'id': id, 'name': name, 'catetory': category}) as c_list\n+from (\n+    select 1 as id, '\u5927\u718a\u732b' as name, '\u718a' as category union all\n+    select 2 as id, '\u5927\u718a\u732b' as name, '\u732b' as category union all\n+    select 3 as id, '\u5c0f\u718a\u732b' as name, '\u732b' as category\n+) t\n+group by category;\n",
  "problem_statement": "An error was encountered using both `distinct` and `struct`\n### What happens?\r\n\r\n![image](https://github.com/user-attachments/assets/4cc06266-e2e5-4088-88a5-013e210788a4)\r\n\r\n\r\n### To Reproduce\r\n\r\n```sql\r\nselect \r\n    category,\r\n    array_agg(distinct name) filter(where id != 5)            as a_list,\r\n    array_agg(name)          filter(where id != 5)            as b_list,\r\n    array_agg({'id': id, 'name': name, 'catetory': category}) as c_list\r\nfrom (\r\n    select 1 as id, '\u5927\u718a\u732b' as name, '\u718a' as category union all\r\n    select 2 as id, '\u5927\u718a\u732b' as name, '\u732b' as category union all\r\n    select 3 as id, '\u5c0f\u718a\u732b' as name, '\u732b' as category\r\n) t\r\ngroup by category;\r\n```\r\n\r\n```console\r\nINTERNAL Error: Attempted to dereference shared_ptr that is NULL!\r\nThis error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.\r\nFor more information, see https://duckdb.org/docs/dev/internal_errors\r\n```\r\n\r\n### OS:\r\n\r\nubuntu/x86_64\r\n\r\n### DuckDB Version:\r\n\r\nv1.1.1 af39bd0dcf\r\n\r\n### DuckDB Client:\r\n\r\ncli\r\n\r\n### Hardware:\r\n\r\n_No response_\r\n\r\n### Full Name:\r\n\r\nicefery\r\n\r\n### Affiliation:\r\n\r\nicefery@163.com\r\n\r\n### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.\r\n\r\nI have not tested with any build\r\n\r\n### Did you include all relevant data sets for reproducing the issue?\r\n\r\nNo - Other reason (please specify in the issue body)\r\n\r\n### Did you include all code required to reproduce the issue?\r\n\r\n- [ ] Yes, I have\r\n\r\n### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?\r\n\r\n- [ ] Yes, I have\nAn error was encountered using both `distinct` and `struct`\n### What happens?\r\n\r\n![image](https://github.com/user-attachments/assets/4cc06266-e2e5-4088-88a5-013e210788a4)\r\n\r\n\r\n### To Reproduce\r\n\r\n```sql\r\nselect \r\n    category,\r\n    array_agg(distinct name) filter(where id != 5)            as a_list,\r\n    array_agg(name)          filter(where id != 5)            as b_list,\r\n    array_agg({'id': id, 'name': name, 'catetory': category}) as c_list\r\nfrom (\r\n    select 1 as id, '\u5927\u718a\u732b' as name, '\u718a' as category union all\r\n    select 2 as id, '\u5927\u718a\u732b' as name, '\u732b' as category union all\r\n    select 3 as id, '\u5c0f\u718a\u732b' as name, '\u732b' as category\r\n) t\r\ngroup by category;\r\n```\r\n\r\n```console\r\nINTERNAL Error: Attempted to dereference shared_ptr that is NULL!\r\nThis error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.\r\nFor more information, see https://duckdb.org/docs/dev/internal_errors\r\n```\r\n\r\n### OS:\r\n\r\nubuntu/x86_64\r\n\r\n### DuckDB Version:\r\n\r\nv1.1.1 af39bd0dcf\r\n\r\n### DuckDB Client:\r\n\r\ncli\r\n\r\n### Hardware:\r\n\r\n_No response_\r\n\r\n### Full Name:\r\n\r\nicefery\r\n\r\n### Affiliation:\r\n\r\nicefery@163.com\r\n\r\n### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.\r\n\r\nI have not tested with any build\r\n\r\n### Did you include all relevant data sets for reproducing the issue?\r\n\r\nNo - Other reason (please specify in the issue body)\r\n\r\n### Did you include all code required to reproduce the issue?\r\n\r\n- [ ] Yes, I have\r\n\r\n### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?\r\n\r\n- [ ] Yes, I have\n",
  "hints_text": "Thanks, I could reproduce it!\nThanks, I could reproduce it!",
  "created_at": "2024-10-09T11:16:13Z"
}